### ISSUE TITLE
wifi_send_pkt_freedom

### ISSUE THREAD

**Issue by georgkreimer** [H-LK/ESP8266-SSID-Text-Broadcast#3]
I think it expect an older SDK since I believe 'wifi_send_pkt_freedom' was remove some time ago.

ESP8266-SSID-Text-Broadcast.ino:75: error: 'wifi_send_pkt_freedom' was not declared in this scope
'wifi_send_pkt_freedom' was not declared in this scope

**Comment by H-LK** [comment]
Just like Kripthor I am using an old version. (2.1.0-rc2). I will add a hint later at the description.

http://arduino.esp8266.com/versions/2.1.0-rc2/package_esp8266com_index.json
