### ISSUE TITLE
How to increase word length?

### ISSUE THREAD

**Issue by milapj** [H-LK/ESP8266-SSID-Text-Broadcast#4]

**Comment by Brice187** [comment]
The words can have a max of 15 chars. The chars are stored in packet[38] - packet[52]

**Comment by Milap7** [comment]
Okay and what if i want to transmit MAC Address? Can you please help me out!

**Comment by milapj** [comment]
Is it possible to transmit SSID and also be connected to a host network at the same time?Need help with this!

**Comment by H-LK** [comment]
I don't know any method where you can be connected to a network and transmit Beacon-Packets at the same time (ESP8266).

To change the length of the SSID change line 26. 0x72 are placeholders. Afterwards increase the packets like Brice187 suggested it.
